apiVersion: v1
kind: Service
metadata:
  name: service-connector
  namespace: platform-apps
  labels:
    app: service-connector
    service: connector
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9092
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
  selector:
    app: service-connector
