apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-apps

bases:
  - ../../base

images:
  - name: service-auth
    newName: service-auth
    newTag: latest

replicas:
  - name: service-auth
    count: 1

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
    target:
      kind: Deployment
      name: service-auth

configMapGenerator:
  - name: service-auth-config
    behavior: merge
    literals:
      - app.env=development
      - log.level=debug
