apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-apps

bases:
  - ../../base

images:
  - name: ghcr.io/atomicads/service-config
    newTag: staging

replicas:
  - name: service-config
    count: 2

configMapGenerator:
  - name: service-config-config
    behavior: merge
    literals:
      - app.env=staging
      - log.level=info
      - otel.samplingRate=0.5
