apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-apps

bases:
  - ../../base

images:
  - name: ghcr.io/atomicads/service-rules
    newTag: v1.0.0

replicas:
  - name: service-rules
    count: 5

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
    target:
      kind: Deployment
      name: service-rules

configMapGenerator:
  - name: service-rules-config
    behavior: merge
    literals:
      - app.env=production
      - log.level=warn
      - otel.samplingRate=0.1
      - features.profiling=false
