apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ClickHouseInstallation
      name: atomicads-clickhouse
    patch: |-
      - op: replace
        path: /spec/templates/volumeClaimTemplates/0/spec/resources/requests/storage
        value: "200Gi"
commonLabels:
  environment: staging
