apiVersion: v1
kind: Service
metadata:
  name: service-rules
  namespace: platform-apps
  labels:
    app: service-rules
    service: rules
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9098
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8008
      targetPort: http
      protocol: TCP
  selector:
    app: service-rules
