apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka-cluster.yaml
  - kafka-topics.yaml

commonLabels:
  app: kafka
  component: streaming
  tier: data
  managed-by: strimzi
