apiVersion: v1
kind: Service
metadata:
  name: service-etl
  namespace: platform-apps
  labels:
    app: service-etl
    service: etl
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9093
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
  selector:
    app: service-etl
