apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: postgresql
      name: atomicads-postgres
    patch: |-
      - op: replace
        path: /spec/numberOfInstances
        value: 1
      - op: replace
        path: /spec/volume/size
        value: "10Gi"
      - op: replace
        path: /spec/volume/storageClass
        value: "hostpath"
      - op: replace
        path: /spec/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/postgresql/parameters/shared_buffers
        value: "128MB"
commonLabels:
  environment: local
