apiVersion: v1
kind: Service
metadata:
  name: service-silver
  namespace: platform-apps
  labels:
    app: service-silver
    service: silver
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8005
      targetPort: http
      protocol: TCP
  selector:
    app: service-silver
