apiVersion: v1
kind: Service
metadata:
  name: service-config
  namespace: platform-apps
  labels:
    app: service-config
    service: config
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9091
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  selector:
    app: service-config
