apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: local

patches:
  - target:
      kind: PersistentVolumeClaim
      name: minio-data
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: hostpath
      - op: replace
        path: /spec/resources/requests/storage
        value: "20Gi"
