apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: platform-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.atomicads.local
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: service-auth
                port:
                  number: 9090
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: service-config
                port:
                  number: 9091
          - path: /connector
            pathType: Prefix
            backend:
              service:
                name: service-connector
                port:
                  number: 9092
