apiVersion: v1
kind: Service
metadata:
  name: service-notification
  namespace: platform-apps
  labels:
    app: service-notification
    service: notification
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9100
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8010
      targetPort: http
      protocol: TCP
  selector:
    app: service-notification
