apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: postgresql
      name: atomicads-postgres
    patch: |-
      - op: replace
        path: /spec/numberOfInstances
        value: 2
      - op: replace
        path: /spec/volume/size
        value: "200Gi"
commonLabels:
  environment: staging
