apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-apps

bases:
  - ../../base

images:
  - name: service-auth
    newName: service-auth
    newTag: staging

replicas:
  - name: service-auth
    count: 2

configMapGenerator:
  - name: service-auth-config
    behavior: merge
    literals:
      - app.env=staging
      - log.level=info
