apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-platform-system.yaml
  - namespace-platform-apps.yaml
  - namespace-platform-data.yaml
  - namespace-platform-monitoring.yaml
  - network-policies.yaml
  - resource-quotas.yaml
  - limit-ranges.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  platform: campaign-lifecycle
