apiVersion: v1
kind: Service
metadata:
  name: service-calculation
  namespace: platform-apps
  labels:
    app: service-calculation
    service: calculation
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9097
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8007
      targetPort: http
      protocol: TCP
  selector:
    app: service-calculation
