apiVersion: v1
kind: Service
metadata:
  name: service-analytics
  namespace: platform-apps
  labels:
    app: service-analytics
    service: analytics
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9099
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8009
      targetPort: http
      protocol: TCP
  selector:
    app: service-analytics
