apiVersion: v1
kind: Service
metadata:
  name: service-auth
  namespace: platform-apps
  labels:
    app: service-auth
    service: auth
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc
  selector:
    app: service-auth
