apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-apps

bases:
  - ../../base

images:
  - name: service-auth
    newName: service-auth
    newTag: v1.0.0

replicas:
  - name: service-auth
    count: 5

configMapGenerator:
  - name: service-auth-config
    behavior: merge
    literals:
      - app.env=production
      - log.level=warn
