apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-data

resources:
  - ../../base

patches:
  # Reduce Kafka replicas and resources for local
  - target:
      kind: Kafka
      name: atomicads-kafka
    patch: |-
      - op: replace
        path: /spec/kafka/replicas
        value: 1
      - op: replace
        path: /spec/kafka/config/offsets.topic.replication.factor
        value: 1
      - op: replace
        path: /spec/kafka/config/transaction.state.log.replication.factor
        value: 1
      - op: replace
        path: /spec/kafka/config/transaction.state.log.min.isr
        value: 1
      - op: replace
        path: /spec/kafka/config/default.replication.factor
        value: 1
      - op: replace
        path: /spec/kafka/config/min.insync.replicas
        value: 1
      - op: replace
        path: /spec/kafka/storage/volumes/0/size
        value: "20Gi"
      - op: replace
        path: /spec/kafka/storage/volumes/0/class
        value: "hostpath"
      - op: replace
        path: /spec/kafka/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/kafka/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/kafka/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/kafka/resources/limits/cpu
        value: "500m"
      - op: remove
        path: /spec/kafka/template/pod/affinity
      - op: replace
        path: /spec/zookeeper/replicas
        value: 1
      - op: replace
        path: /spec/zookeeper/storage/size
        value: "5Gi"
      - op: replace
        path: /spec/zookeeper/storage/class
        value: "hostpath"
      - op: replace
        path: /spec/zookeeper/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/zookeeper/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/zookeeper/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/zookeeper/resources/limits/cpu
        value: "250m"
      - op: remove
        path: /spec/zookeeper/template/pod/affinity
  
  # Reduce topic replicas for local (single broker)
  - target:
      kind: KafkaTopic
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/config/min.insync.replicas
        value: 1

commonLabels:
  environment: local
