apiVersion: v1
kind: Service
metadata:
  name: service-bronze
  namespace: platform-apps
  labels:
    app: service-bronze
    service: bronze
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: grpc
      port: 9094
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8004
      targetPort: http
      protocol: TCP
  selector:
    app: service-bronze
